---
- add_host:
  name: localhost

- hosts: localhost
  become: true
  vars:
    # home: /Users/luka # If macOS
    # home: /home/luka # If linux

  tasks:
    - name: Install system packages
      package:
        name:
          - zsh
          - git
        state: latest

    - name: Set zsh to default shell
      shell: |
        chsh -s "$(command -v zsh)"
        zsh

    - name: Installing / updating `Starship` prompt
      shell: sh -c "$(curl -fsSL https://starship.rs/install.sh)"

    - name: Clone dotfiles
      git:
        repo: 'https://github.com/lukamanitta/dotfiles.git'
        dest: '~/dotfiles'
        recursive: true

    - name: Clean up and install dotfiles
      include: update_dotfiles.yml

    - name: Install `asdf` version manager
      git:
        repo: 'https://github.com/asdf-vm/asdf.git'
        dest: '~/.asdf'

    - name: Install `asdf` plugins for languages
      shell: asdf plugin add {{ item }}
      loop:
        - ruby https://github.com/asdf-vm/asdf-ruby.git
        - nodejs https://github.com/asdf-vm/asdf-nodejs.git
        - rust https://github.com/asdf-community/asdf-rust.git
        - haskell https://github.com/vic/asdf-haskell.git

    - name: Install Debian packages for `ruby-build`
      package:
        - autoconf
        - bison
        - build-essential
        - libssl-dev
        - libyaml-dev
        - libreadline6-dev
        - zlibg1g-dev
        - libncurses5-dev
        - libffi-dev
        - libgdbm6
        - libgdbm-dev
        - libdb-dev
      when: ansible_facts["os_family"] == "Debian"

    - name: Install Homebrew packages for `ruby-build`
      package:
        - openssl
        - readline
      when: ansible_facts["os_family"] == "Darwin"

    - name: Clone `ruby-build`
      git:
        repo: https://github.com/rbenv/ruby-build.git
        dest: "~/.ruby-build"

    - name: Install Debian packages for `asdf nodejs`
      package:
        - dirmngr
        - gpg
        - curl
        - gawk
      when: ansible_facts["os_family"] == "Debian"

    - name: Install Homebrew packages for `asdf nodejs`
      package:
        - gpg
        - gawk
      when: ansible_facts["os_family"] == "Darwin"

    - name: Install languages + neovim with `asdf`
      shell: |
        asdf install {{ item }} latest
        asdf global {{ item }} latest
        source ~/.zshrc
      loop:
        - ruby
        - nodejs
        - rust
        - haskell
