-- vim.pack.add({
--     {
--         src = "https://github.com/oskarrrrrrr/symbols.nvim",
--     },
-- })
--
-- local r = require("symbols.recipes")
-- require("symbols").setup({
--     r.DefaultFilters,
--     r.AsciiSymbols,
--     {
--         sidebar = {
--             open_direction = "right",
--             auto_peek = false,
--             cursor_follow = true,
--             close_on_goto = true,
--         },
--     },
-- })
