#!/bin/bash

# DEBUG_LOG="/tmp/tmux-window-rename-cmd-debug.log"

SHELL_PID=""
RELATIVE_TO=$PWD
COMMAND_STRING=""

for arg in "$@"; do
    case $arg in
        --relative-to)
            shift
            RELATIVE_TO="$1"
            shift
            ;;
        --shell-pid)
            shift
            SHELL_PID="$1"
            shift
            ;;
        --command-string)
            shift
            COMMAND_STRING="$1"
            shift
            ;;
    esac
done

if [ -z "$SHELL_PID" ] && [ -z "$COMMAND_STRING" ]; then
    echo "Error: Requires one of --shell-pid or --command-string"
    exit 1
fi

PROCESS_NAME=""
if [ -n "$COMMAND_STRING" ]; then
    PROCESS_NAME=$(echo "$COMMAND_STRING" | awk '{print $1}' | xargs basename)
else
    PROCESS_NAME=$(pgrep -P "$SHELL_PID" -n -l | grep -vE "tmux|tmux-window-ren" | awk '{print $2}' | xargs basename 2>/dev/null)
fi


if [[ "$PROCESS_NAME" == "ssh" ]]; then
    if [ -n "$COMMAND_STRING" ]; then
        SSH_ARGS="$COMMAND_STRING"
    else
        SSH_ARGS=$(pgrep -P "$SHELL_PID" -n -a | sed "s/^[0-9]* //" | grep "ssh")
    fi

    # Ignore the first word (ssh), then find the first argument
    # that does NOT start with '-' (the flags).
    SSH_DESTINATION=$(echo "$SSH_ARGS" | awk '{
        for (i=2; i<=NF; i++) {
            if ($i !~ /^-/) {
                print $i;
                exit;
            }
        }
    }')

    if [ -n "$SSH_DESTINATION" ]; then
        echo "[󰌘 $SSH_DESTINATION]"
        exit 0
    fi
fi

PROCESS_NAME=" $PROCESS_NAME"

echo "[$(git-aware-formatted-cwd --relative-to $RELATIVE_TO --icons --bold --tmux)]$PROCESS_NAME"
