#!/bin/bash

# check for --relative-to and --command-pid
SHELL_PID=""
RELATIVE_TO=""

for arg in "$@"; do
    case $arg in
        --relative-to)
            shift
            RELATIVE_TO="$1"
            shift
            ;;
        --command-pid)
            shift
            SHELL_PID="$1"
            shift
            ;;
    esac
done

TTY_NAME=""
if [ -n "$SHELL_PID" ]; then
    TTY_NAME=$(ps -p "$SHELL_PID" -o tty= | tr -d ' ')
fi

PROCESS_NAME=""
if [ -n "$TTY_NAME" ]; then
    PROCESS_NAME+=" "
    PROCESS_NAME+=$(ps -t "$TTY_NAME" -o comm= | grep -vE "fish|bash|sh|ps|grep|sed|awk|sleep|tail" | tail -n 1 | awk -F'/' '{print $NF}')
fi

if [ -n "$RELATIVE_TO" ]; then
    echo "[$(git-aware-formatted-cwd --relative-to $RELATIVE_TO --icons --bold --tmux)]$PROCESS_NAME"
    exit 0
fi

echo "[$(git-aware-formatted-cwd --icons --bold --tmux)]$PROCESS_NAME"
