[colourme]
; topbar
topbar              = 1d1d1d
topbar-text         = ebdbb2
topbar-subtext      = 7a7a7a
tab-active          = 3c3836
tab-active-text     = ebdbb2
tab-hover           = 504945
topbar-border       = 1d1d1d

; sidebars
; sidebar             = 282828
; sidebar             = 1d1d1d
sidebar             = 3c3836
sidebar-text        = ebdbb2
link-hover-text     = 6d6d6d
link-active         = 504945
link-active-text    = e8e8e8
sidebar-border      = 1d1d1d

; main view
main                = 282828
text                = ebdbb2
subtext             = 928374
selected-row        = d79921

; player bar
; player              = 282828
player             = 1d1d1d
player-text         = ebdbb2
player-subtext      = ebdbb2
player-selected-row = d79921
player-border       = 1d1d1d

; accent colors
button-active       = d79921

; others
button              = d79921
button-disabled     = 3c3836
scrollbar           = 3c3836
scrollbar-hover     = fbf1c7
context-menu        = 1d1d1d
context-menu-text   = ebdbb2
context-menu-hover  = 282828
card                = 504945
shadow              = 504945
notification        = 504945
notification-error  = cc241d
misc                = 282828

; ylx
main-elevated       = 3c3836
highlight-elevated  = 504945
highlight           = 504945
