[colourme]
; topbar
topbar              = 121019
topbar-text         = e0def4
topbar-subtext      = 7a7a7a
tab-active          = 1f1d2e
tab-active-text     = e0def4
tab-hover           = 26233a
topbar-border       = 1f1d2e

; sidebars
; sidebar             = 191724
; sidebar             = 121019
sidebar             = 1f1d2e
sidebar-text        = e0def4
link-hover-text     = 6d6d6d
link-active         = 26233a
link-active-text    = e8e8e8
sidebar-border      = 1f1d2e

; main view
main                = 191724
text                = e0def4
subtext             = 908caa
selected-row        = eb6f92

; player bar
; player              = 191724
player             = 121019
player-text         = e0def4
player-subtext      = e0def4
player-selected-row = eb6f92
player-border       = 1f1d2e

; accent colors
button-active       = eb6f92

; others
button              = eb6f92
button-disabled     = 1f1d2e
scrollbar           = 1f1d2e
scrollbar-hover     = e0def4
context-menu        = 121019
context-menu-text   = e0def4
context-menu-hover  = 191724
card                = 26233a
shadow              = 26233a
notification        = 26233a
notification-error  = eb6f92
misc                = 191724

; ylx
main-elevated       = 1f1d2e
highlight-elevated  = 26233a
highlight           = 26233a
