[colourme]
; topbar
topbar              = 1a1b2a
topbar-text         = c8d3f5
topbar-subtext      = 7a7a7a
tab-active          = 1e2030
tab-active-text     = c8d3f5
tab-hover           = 2f334d
topbar-border       = 1a1b2a

; sidebars
; sidebar             = 222436
; sidebar             = 1a1b2a
sidebar             = 1e2030
sidebar-text        = c8d3f5
link-hover-text     = 6d6d6d
link-active         = 2f334d
link-active-text    = e8e8e8
sidebar-border      = 1a1b2a

; main view
main                = 222436
text                = c8d3f5
subtext             = 828bb8
selected-row        = c099ff

; player bar
; player              = 222436
player             = 1a1b2a
player-text         = c8d3f5
player-subtext      = c8d3f5
player-selected-row = c099ff
player-border       = 1a1b2a

; accent colors
button-active       = c099ff

; others
button              = c099ff
button-disabled     = 1e2030
scrollbar           = 1e2030
scrollbar-hover     = b4c2f0
context-menu        = 1a1b2a
context-menu-text   = c8d3f5
context-menu-hover  = 222436
card                = 2f334d
shadow              = 2f334d
notification        = 2f334d
notification-error  = c099ff
misc                = 222436

; ylx
main-elevated       = 1e2030
highlight-elevated  = 2f334d
highlight           = 2f334d
