local U = {}
-- Color table for highlights
local colors = {
    normal = "#cba6f7",
    insert = "#89b4fa",
    visual = "#eba0ac",
    visual_line = "#f38ba8",
    a = "#f5e0dc",
    b = "#94e2d5",
    c = "#f5c2e7",
    d = "#fab387",
    e = "#a6e3a1",
}
-- TODO: make these use theme colours and no more blue please
U.mode_colour = {
    n = colors.normal,
    i = colors.insert,
    v = colors.visual,
    [""] = colors.a,
    V = colors.visual_line,
    c = colors.e,
    no = colors.visual,
    s = colors.c,
    S = colors.c,
    [""] = colors.c,
    ic = colors.a,
    R = colors.d,
    Rv = colors.d,
    cv = colors.visual,
    ce = colors.visual,
    r = colors.visual_line,
    rm = colors.visual_line,
    ["r?"] = colors.visual_line,
    ["!"] = colors.visual,
    t = colors.visual,
}

U.mode_shortnames = {
    n = "N",
    no = "N?",
    nov = "N?",
    noV = "N?",
    ["no\22"] = "N?",
    niI = "Ni",
    niR = "Nr",
    niV = "Nv",
    nt = "Nt",
    v = "V",
    vs = "Vs",
    V = "V_",
    Vs = "Vs",
    ["\22"] = "^V",
    ["\22s"] = "^V",
    s = "S",
    S = "S_",
    ["\19"] = "^S",
    i = "I",
    ic = "Ic",
    ix = "Ix",
    R = "R",
    Rc = "Rc",
    Rx = "Rx",
    Rv = "Rv",
    Rvc = "Rv",
    Rvx = "Rv",
    c = "C",
    cv = "Ex",
    r = "...",
    rm = "M",
    ["r?"] = "?",
    ["!"] = "!",
    t = "T",
}

return U
