[colors]
ansi = [
    "#45475a", # Black
    "#f38ba8", # Red
    "#a6e3a1", # Green
    "#f9e2af", # Yellow
    "#89b4fa", # Blue
    "#f5c2e7", # Magenta
    "#94e2d5", # Cyan
    "#bac2de", # White
]

brights = [
    "#585b70", # Black
    "#f38ba8", # Red
    "#a6e3a1", # Green
    "#f9e2af", # Yellow
    "#89b4fa", # Blue
    "#f5c2e7", # Magenta
    "#94e2d5", # Cyan
    "#a6adc8", # White
]

background = "#1e1e2e"
foreground = "#cdd6f4"

cursor_bg = "#cdd6f4"
cursor_fg = "#1e1e2e"
cursor_border = "#cdd6f4"

scrollbar_thumb = "#45475a"

selection_bg = "#45475a"
selection_fg = "#cdd6f4"

split = "#45475a"
visual_bell = "#45475a"

[colors.indexed]

[colors.tab_bar]
background = "#1e1e2e"
inactive_tab_edge = "#1e1e2e"

[colors.tab_bar.active_tab]
bg_color = "#1e1e2e"
fg_color = "#cdd6f4"

intensity = "Bold"      # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = false
strikethrough = false

[colors.tab_bar.inactive_tab]
bg_color = "#1e1e2e"
fg_color = "#585b70"

intensity = "Normal"    # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = true
strikethrough = false

[colors.tab_bar.inactive_tab_hover]
bg_color = "#1e1e2e"
fg_color = "#cdd6f4"

intensity = "Normal"    # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = true
strikethrough = false

[colors.tab_bar.new_tab]
bg_color = "#1e1e2e"
fg_color = "#585b70"

intensity = "Normal"    # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = false
strikethrough = false

[colors.tab_bar.new_tab_hover]
bg_color = "#1e1e2e"
fg_color = "#cdd6f4"

intensity = "Normal"    # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = false
strikethrough = false