[colors]
ansi = [
    "#1d2021", # Black
    "#cc241d", # Red
    "#98971a", # Green
    "#d79921", # Yellow
    "#458588", # Blue
    "#b16286", # Magenta
    "#689d6a", # Cyan
    "#f9f5d7", # White
]

brights = [
    "#7c6f64", # Black
    "#fb4934", # Red
    "#b8bb26", # Green
    "#fabd2f", # Yellow
    "#83a598", # Blue
    "#d3869b", # Magenta
    "#8ec07c", # Cyan
    "#ebdbb2", # White
]

background = "#1d2021"
foreground = "#f9f5d7"

cursor_bg = "#f9f5d7"
cursor_fg = "#1d2021"
cursor_border = "#f9f5d7"

scrollbar_thumb = "#1d2021"

selection_bg = "#665c54"
selection_fg = "#f9f5d7"

split = "#1d2021"
visual_bell = "#1d2021"

[colors.indexed]

[colors.tab_bar]
background = "#1d2021"
inactive_tab_edge = "#1d2021"

[colors.tab_bar.active_tab]
bg_color = "#1d2021"
fg_color = "#f9f5d7"

intensity = "Bold"      # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = false
strikethrough = false

[colors.tab_bar.inactive_tab]
bg_color = "#1d2021"
fg_color = "#7c6f64"

intensity = "Normal"    # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = true
strikethrough = false

[colors.tab_bar.inactive_tab_hover]
bg_color = "#1d2021"
fg_color = "#f9f5d7"

intensity = "Normal"    # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = true
strikethrough = false

[colors.tab_bar.new_tab]
bg_color = "#1d2021"
fg_color = "#7c6f64"

intensity = "Normal"    # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = false
strikethrough = false

[colors.tab_bar.new_tab_hover]
bg_color = "#1d2021"
fg_color = "#f9f5d7"

intensity = "Normal"    # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = false
strikethrough = false