[colors]
ansi = [
    "#16161d", # Black
    "#c34043", # Red
    "#76946a", # Green
    "#c0a36e", # Yellow
    "#7e9cd8", # Blue
    "#957fb8", # Magenta
    "#6a9589", # Cyan
    "#c8c093", # White
]

brights = [
    "#727169", # Black
    "#e82424", # Red
    "#98bb6c", # Green
    "#e6c384", # Yellow
    "#7fb4ca", # Blue
    "#938aa9", # Magenta
    "#7aa89f", # Cyan
    "#dcd7ba", # White
]

background = "#1f1f28"
foreground = "#dcd7ba"

cursor_bg = "#c8c093"
cursor_fg = "#c8c093"
cursor_border = "#c8c093"

scrollbar_thumb = "#16161d"

selection_bg = "#2d4f67"
selection_fg = "#c8c093"

split = "#16161d"
visual_bell = "#16161d"

[colors.indexed]

[colors.tab_bar]
background = "#1f1f28"
inactive_tab_edge = "#1f1f28"

[colors.tab_bar.active_tab]
bg_color = "#1f1f28"
fg_color = "#dcd7ba"

intensity = "Bold"      # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = false
strikethrough = false

[colors.tab_bar.inactive_tab]
bg_color = "#1f1f28"
fg_color = "#727169"

intensity = "Normal"    # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = true
strikethrough = false

[colors.tab_bar.inactive_tab_hover]
bg_color = "#1f1f28"
fg_color = "#dcd7ba"

intensity = "Normal"    # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = true
strikethrough = false

[colors.tab_bar.new_tab]
bg_color = "#1f1f28"
fg_color = "#727169"

intensity = "Normal"    # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = false
strikethrough = false

[colors.tab_bar.new_tab_hover]
bg_color = "#1f1f28"
fg_color = "#dcd7ba"

intensity = "Normal"    # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = false
strikethrough = false