[colors]
ansi = [
    "#190a01", # Black
    "#b03726", # Red
    "#e07b32", # Green
    "#f1a335", # Yellow
    "#40344c", # Blue
    "#df5f66", # Magenta
    "#815c41", # Cyan
    "#e2d7d0", # White
]

brights = [
    "#756c67", # Black
    "#e9523f", # Red
    "#e6955b", # Green
    "#f4b55d", # Yellow
    "#665d70", # Blue
    "#f9797f", # Magenta
    "#9a7d67", # Cyan
    "#ebdbb2", # White
]

background = "#190a01"
foreground = "#e2d7d0"

cursor_bg = "#e2d7d0"
cursor_fg = "#190a01"
cursor_border = "#e2d7d0"

scrollbar_thumb = "#190a01"

selection_bg = "#a6511e"
selection_fg = "#e2d7d0"

split = "#190a01"
visual_bell = "#190a01"

[colors.indexed]

[colors.tab_bar]
background = "#190a01"
inactive_tab_edge = "#190a01"

[colors.tab_bar.active_tab]
bg_color = "#190a01"
fg_color = "#e2d7d0"

intensity = "Bold"      # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = false
strikethrough = false

[colors.tab_bar.inactive_tab]
bg_color = "#190a01"
fg_color = "#756c67"

intensity = "Normal"    # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = true
strikethrough = false

[colors.tab_bar.inactive_tab_hover]
bg_color = "#190a01"
fg_color = "#e2d7d0"

intensity = "Normal"    # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = true
strikethrough = false

[colors.tab_bar.new_tab]
bg_color = "#190a01"
fg_color = "#756c67"

intensity = "Normal"    # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = false
strikethrough = false

[colors.tab_bar.new_tab_hover]
bg_color = "#190a01"
fg_color = "#e2d7d0"

intensity = "Normal"    # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = false
strikethrough = false