$font = Roboto Mono, "Symbols Nerd Font Mono", monospace

$activeBorderColor = rgba(815c14ff)

$background = rgba(1d1d1dff)
$foreground = rgba(928374ff)

$success = rgba(98971aff)
$failure = rgba(cc241dff)
