$font = Roboto Mono, "Symbols Nerd Font Mono", monospace

$activeBorderColor = rgba(8d4358ff)

$background = rgba(191724ff)
$foreground = rgba(908caaff)

$success = rgba(31748fff)
$failure = rgba(eb6f92ff)
