$font = Roboto Mono, "Symbols Nerd Font Mono", monospace

$activeBorderColor = rgba(815c14ff)

$background = rgba(282828ff)
$foreground = f9f5d7ff

$success = rgba(98971aff)
$failure = rgba(cc241dff)
