#Insert blank line between shell prompts
add_newline = true

#Format
format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_state\
$git_metrics\
$git_status\
$package\
$java\
$nodejs\
$python\
$ruby\
$rust \
$cmd_duration\
$line_break\
$character
"""

#Module settings
[time]
disabled = false
use_12hr = true

[directory]
read_only = " "

[git_branch]
symbol = " "

[git_metrics]
disabled = false
added_style = "bold green"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
format='$ahead$behind $staged $modified $untracked $stashed '
ahead = '[⇡$count](green)'
behind = '[⇣$count](green)'
untracked = '[?$count](blue)'
stashed = '[*](green)'
modified = '[!$count](bold yellow)'
staged = '[+$count](bold yellow)'


[hg_branch]
symbol = " "

[java]
symbol = " "

[memory_usage]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[shlvl]
symbol = " "
