background =   "#"
foreground =   "#"

cursor_bg =    "#"
cursor_fg =    "#"

selection_bg = "#"
selection_fg = "#"

[regular]
black =   "#"
red =     "#"
green =   "#"
yellow =  "#"
blue =    "#"
magenta = "#"
cyan =    "#"
white =   "#"

[bright]
black =   "#"
red =     "#"
green =   "#"
yellow =  "#"
blue =    "#"
magenta = "#"
cyan =    "#"
white =   "#"