[colours]
background =   "#1f2430"
foreground =   "#cbccc6"

cursor_bg =    "#cbccc6"
cursor_fg =    "#1f2430"

selection_bg = "#33415e"
selection_fg = "#cbccc6"

[colours.regular]
black =   "#1f2430"
red =     "#f28779"
green =   "#bae67e"
yellow =  "#ffcc66"
blue =    "#5ccfe6"
magenta = "#d4bfff"
cyan =    "#95e6cb"
white =   "#cbccc6"

[colours.bright]
black =   "#607080"
red =     "#ff3333"
green =   "#bae67e"
yellow =  "#ffcc66"
blue =    "#5ccfe6"
magenta = "#d4bfff"
cyan =    "#95e6cb"
white =   "#5c6773"