background =   "#1e1e2e"
foreground =   "#cdd6f4"

cursor_bg =    "#cdd6f4"
cursor_fg =    "#1e1e2e"

selection_bg = "#45475a"
selection_fg = "#cdd6f4"

[regular]
black =   "#45475a"
red =     "#f38ba8"
green =   "#a6e3a1"
yellow =  "#f9e2af"
blue =    "#89b4fa"
magenta = "#f5c2e7"
cyan =    "#94e2d5"
white =   "#bac2de"

[bright]
black =   "#585b70"
red =     "#f38ba8"
green =   "#a6e3a1"
yellow =  "#f9e2af"
blue =    "#89b4fa"
magenta = "#f5c2e7"
cyan =    "#94e2d5"
white =   "#a6adc8"
