background =   "#190a01"
foreground =   "#e2d7d0"

cursor_bg =    "#e2d7d0"
cursor_fg =    "#190a01"

selection_bg = "#a6511e"
selection_fg = "#e2d7d0"

accent =       "#cf6525"

[regular]
black =   "#190a01"
red =     "#b03726"
# green =   "#cf6525"
green =   "#e07b32"
yellow =  "#f1a335"
blue =    "#40344c"
magenta = "#df5f66"
cyan =    "#815c41"
white =   "#e2d7d0"

[bright]
black =   "#756c67"
red =     "#e9523f"
green =   "#e6955b"
yellow =  "#f4b55d"
blue =    "#665d70"
magenta = "#f9797f"
cyan =    "#9a7d67"
white =   "#ebdbb2"
