background =   "#282828"
foreground =   "#f9f5d7"

cursor_bg =    "#f9f5d7"
cursor_fg =    "#282828"

selection_bg = "#665c54"
selection_fg = "#f9f5d7"

accent =       "#d79921"
accent_alt_1 = "#98971a"
accent_alt_2 = "#689d6a"

vim_background = "dark"
vim_name = "Gruvbox"

wallpaper = "~/.wallpaper/gruvbox/flower-pot.jpg"

base00 = "#282828"
base01 = "#3c3836"
base02 = "#504945"
base03 = "#665c54"
base04 = "#928374"
base05 = "#ebdbb2"
base06 = "#fbf1c7"
base07 = "#f9f5d7"
base08 = "#cc241d"
base09 = "#d65d0e"
base0A = "#d79921"
base0B = "#98971a"
base0C = "#689d6a"
base0D = "#458588"
base0E = "#b16286"
base0F = "#9d0006"
base10 = "#2a2520"
base11 = "#1d1d1d"
base12 = "#fb4934"
base13 = "#fabd2f"
base14 = "#b8bb26"
base15 = "#8ec07c"
base16 = "#83a598"
base17 = "#d3869b"

[regular]
black =   "#282828"
red =     "#cc241d"
green =   "#98971a"
yellow =  "#d79921"
blue =    "#458588"
magenta = "#b16286"
cyan =    "#689d6a"
white =   "#f9f5d7"

[bright]
black =   "#7c6f64"
red =     "#fb4934"
green =   "#b8bb26"
yellow =  "#fabd2f"
blue =    "#83a598"
magenta = "#d3869b"
cyan =    "#8ec07c"
white =   "#ebdbb2"
