background =   "#282828"
foreground =   "#f9f5d7"

cursor_bg =    "#f9f5d7"
cursor_fg =    "#282828"

selection_bg = "#665c54"
selection_fg = "#f9f5d7"

accent =       "#d79921"

[regular]
black =   "#282828"
red =     "#cc241d"
green =   "#98971a"
yellow =  "#d79921"
blue =    "#458588"
magenta = "#b16286"
cyan =    "#689d6a"
white =   "#f9f5d7"

[bright]
black =   "#7c6f64"
red =     "#fb4934"
green =   "#b8bb26"
yellow =  "#fabd2f"
blue =    "#83a598"
magenta = "#d3869b"
cyan =    "#8ec07c"
white =   "#ebdbb2"
