[colours]
background =   "#1f1f28"
foreground =   "#dcd7ba"

cursor_bg =    "#c8c093"
cursor_fg =    "#c8c093"

selection_bg = "#2d4f67"
selection_fg = "#c8c093"

[colours.regular]
black =   "#16161d"
red =     "#c34043"
green =   "#76946a"
yellow =  "#c0a36e"
blue =    "#7e9cd8"
magenta = "#957fb8"
cyan =    "#6a9589"
white =   "#c8c093"

[colours.bright]
black =   "#727169"
red =     "#e82424"
green =   "#98bb6c"
yellow =  "#e6c384"
blue =    "#7fb4ca"
magenta = "#938aa9"
cyan =    "#7aa89f"
white =   "#dcd7ba"
