colorscheme kanagawa

# Statusline on top
set global ui_options terminal_status_on_top=yes

# Cat
set global ui_options terminal_assistant=cat

add-highlighter global/ number-lines -relative -hlcursor -separator "   " -cursor-separator "  " -min-digits 3
add-highlighter global/ wrap
add-highlighter global/ show-matching

# Indentation
set-option global tabstop     4
set-option global indentwidth 4

# Scrolloff
set-option global scrolloff   6,4

# Tabs to spaces
hook global InsertChar \t %{
    exec -draft h@
}

# jk to exit insert mode
hook global InsertChar k %{ try %{
    exec -draft hH <a-k>jk<ret> d
    exec <esc>
}}

# Comment keybind
map global normal "#" ":comment-line<ret>"

# 'Find' user mode
define-command -hidden -docstring "run a fzf command and save output to tmp file" \
run-fzf-cmd -params .. %{
    suspend-and-resume \
        "%arg{@} > /tmp/fzf-files-%val{client_pid}" \
        "for-each-line edit /tmp/fzf-files-%val{client_pid}"
}

declare-user-mode find
map global user f ":enter-user-mode find<ret>" -docstring "enter find mode"
map global find f ":run-fzf-cmd 'fzf'<ret>"
#   fzf grep
#   fzf files (smart git search)

# Ranger
define-command open-ranger %{
    suspend-and-resume \
        "ranger --choosefiles=/tmp/ranger-files-%val{client_pid}" \
        "for-each-line edit /tmp/ranger-files-%val{client_pid}"
}
map global user e ':open-ranger<ret>' -docstring 'select files in ranger'

# Lazygit
map global user g ':suspend-and-resume "lazygit"<ret>' -docstring 'open LazyGit'

# kak-lsp
# source "$HOME"/.config/kak/kak-lsp/kak-lsp.kak
eval %sh{kak-lsp --config $HOME/.config/kak/kak-lsp/kak-lsp.toml --kakoune -s $kak_session}
# set global lsp_cmd "kak-lsp -s %val{session} -vvv --log /tmp/kak-lsp.log"
 
map global user l %{:enter-user-mode lsp<ret>} -docstring "LSP mode"

hook global WinSetOption filetype=(rust|python|javascript|typescript|dart|svelte) %{
    lsp-enable-window
    lsp-inlay-hints-enable global
    # hook global BufWritePre .* lsp-formatting-sync
}
#   set icons
set-option global lsp_diagnostic_line_error_sign ""
set-option global lsp_diagnostic_line_warning_sign ""
set-option global lsp_diagnostic_line_hint_sign ""
set-option global lsp_diagnostic_line_info_sign ""
set-option global lsp_code_lens_sign ""
set-option global lsp_inlay_diagnostic_sign ""

# wezterm.kak
wezterm-integration-enable
set-option global wezterm_terminal_default wezterm-terminal-horizontal


