# !! try to keep this minimal please

# Relative line numbers
hook global BufCreate .* %[
    add-highlighter buffer/ number-lines -relative -hlcursor
    add-highlighter buffer/ wrap
]

# indentation
set-option global tabstop     4
set-option global indentwidth 4

# scrolloff
set-option global scrolloff   6,0

# tabs to spaces
hook global InsertChar \t %{
    exec -draft h@
}

# jk to exit insert mode
hook global InsertChar k %{ try %{
    exec -draft hH <a-k>jk<ret> d
    exec <esc>
}}
