colorscheme Gruvbox

# Statusline on top
set-option -add global ui_options terminal_status_on_top=yes

# Cat
set-option -add global ui_options terminal_assistant=cat

add-highlighter global/ number-lines -relative -hlcursor -separator "   " -cursor-separator "  " -min-digits 3
add-highlighter global/ wrap
add-highlighter global/ show-matching

# Indentation
set-option global tabstop     4
set-option global indentwidth 4

# Scrolloff
set-option global scrolloff   6,4

# Tabs to spaces
hook global InsertChar \t %{
    exec -draft h@
}

# jk to exit insert mode
hook global InsertChar k %{ try %{
    exec -draft hH <a-k>jk<ret> d
    exec <esc>
}}

# Comment keybind
map global normal "#" ":comment-line<ret>"

# Ranger
define-command open-ranger %{
    suspend-and-resume \
        "ranger --choosefiles=/tmp/ranger-files-%val{client_pid}" \
        "for-each-line edit /tmp/ranger-files-%val{client_pid}"
}
map global user e ":open-ranger<ret>" -docstring "select files in ranger"

# Lazygit
map global user g ":suspend-and-resume 'lazygit'<ret>" -docstring "open LazyGit"

# wezterm.kak
wezterm-integration-enable
set-option global wezterm_terminal_default wezterm-terminal-horizontal
