require("mkdnflow").setup({
    modules = {
        bib = false,
        buffers = false,
        conceal = false,
        cursor = true,
        folds = false,
        links = true,
        lists = true,
        maps = true,
        paths = true,
        tables = false,
    },
    create_dirs = true,
    perspective = {
        priority = "current",
        fallback = "root",
        root_tell = ".zk/",
    },
    filetypes = { md = true, rmd = true, markdown = true },
    wrap = true,
    -- bib = {
    --    default_path = "bibliography.bib",
    -- },
    links = {
        style = "markdown",
        conceal = true,
    },
    to_do = {
        symbols = { " ", "-", "X" },
        update_parents = true,
        not_started = " ",
        in_progress = "-",
        complete = "X",
    },
    mappings = {
        -- MkdnEnter = { { "n", "v" }, "<CR>" },
        MkdnTab = false,
        MkdnSTab = false,
        MkdnNextLink = { "n", "<Tab>" },
        MkdnPrevLink = { "n", "<S-Tab>" },
        MkdnNextHeading = { "n", "]]" },
        MkdnPrevHeading = { "n", "[[" },
        MkdnFollowLink = false, -- see MkdnEnter
        MkdnDestroyLink = { "n", "<M-CR>" },
        MkdnTagSpan = { "v", "<M-CR>" },
        MkdnMoveSource = { "n", "<F2>" },
        MkdnYankAnchorLink = { "n", "ya" },
        MkdnYankFileAnchorLink = { "n", "yfa" },
        MkdnIncreaseHeading = { "n", "+" },
        MkdnDecreaseHeading = { "n", "-" },
        MkdnToggleToDo = { { "n", "v" }, "<C-Space>" },
        MkdnNewListItem = false,
        MkdnExtendList = false,
        MkdnUpdateNumbering = { "n", "<leader>nn" },
        MkdnTableNextCell = { "i", "<Tab>" },
        MkdnTablePrevCell = { "i", "<S-Tab>" },
        MkdnTableNextRow = false,
        MkdnTablePrevRow = { "i", "<M-CR>" },
        MkdnTableNewRowBelow = { { "n", "i" }, "<leader>ir" },
        MkdnTableNewRowAbove = { { "n", "i" }, "<leader>iR" },
        MkdnTableNewColAfter = { { "n", "i" }, "<leader>ic" },
        MkdnTableNewColBefore = { { "n", "i" }, "<leader>iC" },
        MkdnFoldSection = { "n", "<leader>f" },
        MkdnUnfoldSection = { "n", "<leader>F" },
    },
})
