$font = Roboto Mono, "Symbols Nerd Font Mono", monospace

$activeBorderColor = rgba({{hexa: multiply_brightness(random_select(accent, accent_alt_1, accent_alt_2), 0.6) || hexa: multiply_brightness(accent, 0.6)}})

$background = rgba({{hexa: background}})
$foreground = {{hexa: foreground}}

$success = rgba({{hexa: regular.green}})
$failure = rgba({{hexa: regular.red}})
