[colourme]
; topbar
topbar              = {{hex: base11 || hex: multiply_brightness(base00, 0.7) || hex: multiply_brightness(background, 0.7)}}
topbar-text         = {{hex: base05 || hex: foreground}}
topbar-subtext      = 7a7a7a
tab-active          = {{hex: base01 || hex: regular.black}}
tab-active-text     = {{hex: base05 || hex: foreground}}
tab-hover           = {{hex: base02 || hex: background}}
topbar-border       = {{hex: base11 || hex: base01 || hex:regular.black}}

; sidebars
; sidebar             = {{hex: base00 || hex: background}}
; sidebar             = {{hex: base11 || hex: multiply_brightness(base00, 0.7) || hex: multiply_brightness(background, 0.7)}}
sidebar             = {{hex: base01 || hex: regular.black}}
sidebar-text        = {{hex: base05 || hex: foreground}}
link-hover-text     = 6d6d6d
link-active         = {{hex: base02 || hex: bright.black}}
link-active-text    = e8e8e8
sidebar-border      = {{hex: base11 || hex: base01 || hex:regular.black}}

; main view
main                = {{hex: base00 || hex: background}}
text                = {{hex: base05 || hex: foreground}}
subtext             = {{hex: base04 || hex: multiply_brightness(foreground, 0.8)}}
selected-row        = {{hex: accent}}

; player bar
; player              = {{hex: base00 || hex: background}}
player             = {{hex: base11 || hex: multiply_brightness(base00, 0.7) || hex: multiply_brightness(background, 0.7)}}
player-text         = {{hex: base05 || hex: foreground}}
player-subtext      = {{hex: base05 || hex: foreground}}
player-selected-row = {{hex: accent}}
player-border       = {{hex: base11 || hex: base01 || hex:regular.black}}

; accent colors
button-active       = {{hex: accent}}

; others
button              = {{hex: accent}}
button-disabled     = {{hex: base01 || hex: regular.black}}
scrollbar           = {{hex: base01 || hex: regular.black}}
scrollbar-hover     = {{hex: base06 || hex: foreground}}
context-menu        = {{hex: base11 || hex: multiply_brightness(base00, 0.7) || hex: multiply_brightness(background, 0.7)}}
context-menu-text   = {{hex: base05 || hex: foreground}}
context-menu-hover  = {{hex: base00 || hex: background}}
card                = {{hex: base02 || hex: bright.black}}
shadow              = {{hex: base02 || hex: bright.black}}
notification        = {{hex: base02 || hex: bright.black}}
notification-error  = {{hex: base08 || hex: regular.red}}
misc                = {{hex: base00 || hex: background}}

; ylx
main-elevated       = {{hex: base01 || hex: regular.black}}
highlight-elevated  = {{hex: base02 || hex: background}}
highlight           = {{hex: base02 || hex: background}}
