local icons = {
    Color = ' ',
    Constant = ' ',
    EnumMember = ' ',
    Field = ' ',
    Folder = ' ',
    Function = ' ',
    Keyword = ' ',
    Method = ' ',
    Module = ' ',
    Property = ' ',
    Struct = ' ',
    Text = ' ',
    Value = ' ',
    Variable = ' ',
    Constructor = '',
    Class = 'ﴯ',
    Interface = '',
    Unit = '',
    Enum = '',
    Snippet = '',
    File = '',
    Reference = '',
    Event = '',
    Operator = '',
    TypeParameter = '',

    LspError = ' ',
    LspWarn = ' ',
    LspHint = ' ',
    LspInfo = ' ',
    LspCodeAction = '',
    -- LspError = ' ',
    -- LspWarn = ' ',
    -- LspHint = ' ',
    -- LspInfo = ' ',
    -- LspCodeAction = '',
}

return icons
